FROM node:10.19.0-alpine3.11

# faz da pasta 'app' o diretório atual de trabalho
WORKDIR /frontend

# copia os arquivos 'package.json' e 'package-lock.json' (se disponível)
COPY package*.json ./

# instala dependências do projeto
RUN npm install

# copia arquivos e pastas para o diretório atual de trabalho (pasta 'app')
COPY . .

EXPOSE 8080
CMD [ "npm", "start" ]