version: "3.7"

services:
  research:
    build:
      context: ./research
      dockerfile: Dockerfile
    command: poetry run start
    volumes:
      - ./research/:/research/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    command: poetry run test
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/frontend/
      - /frontend/node_modules
    ports:
      - 3000:3000

  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    command: npm run test -- --watchAll=false
    volumes:
      - ./frontend/:/frontend/
      - /frontend/node_modules
    ports:
      - 8080:8080
