name: Continuous Integration

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Backend Images
        run: docker-compose build backend
      - name: Run Test Backend Pipeline
        run: docker-compose exec -T backend poetry run test
