name: Continuous Integration

on: [pull_request]

jobs:
  backend:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Build Backend Images
        run: docker-compose build backend-test
      - name: Run Test Backend Pipeline
        run: docker-compose run backend-test poetry run test
